### ISSUE TITLE
Fix WebException in - [HttpWebRequest EndGetResponse(System.IAsyncResult asyncResult)]

### ISSUE THREAD

**Issue by aditmer** [aditmer/NightscoutHybridMobile#7] opened 2016-12-16 19:35 UTC
### Stacktrace ###

<pre>0 System.Net HttpWebRequest EndGetResponse 1 System.Threading.Tasks TaskFactory`1[TResult] FromAsyncCoreLogic null 0 </pre>

### Reason ###

System.Net.WebException: Error: NameResolutionFailure

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149750654](https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149750654)

**Comment by srmoss** [comment] 2016-12-16 20:18
Duplicate of #8

**Closed as completed by srmoss** 2016-12-16 20:18 UTC
